'use client';
import {useEffect,useRef,useState} from 'react';
import {CalendarDays,BookOpen,Layers3,ChartNoAxesCombined,Check,ChevronLeft,ChevronRight,Clock3,Search,ExternalLink,RefreshCw,CheckCheck} from 'lucide-react';
import plan from './plan.json';
type Entry={lesson?:boolean;practice?:boolean;pyqs?:boolean;revision?:boolean;done?:boolean;hours?:number|null;notes?:string};
type Progress=Record<string,Entry>;
type View='Today'|'Syllabus'|'Modules'|'Progress';
const stages=['lesson','practice','pyqs','revision'] as const;
const stageLabels=['Lesson','Practice','PYQs','Revision'];
const subjects=[...new Set(plan.modules.map(m=>m.subject))];
const dates=[...new Set(plan.tasks.map(t=>t.date))];
const colors=['#2f7c75','#416eb2','#8b65a7','#b77c32','#467f9d','#a35c77','#5b7d45','#727aa3'];
const actualToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const clampDate=(d:string)=>d<dates[0]?dates[0]:d>dates.at(-1)!?dates.at(-1)!:d;
const pretty=(d:string,long=false)=>new Intl.DateTimeFormat('en-IN',{day:'numeric',month:long?'long':'short',...(long?{weekday:'long' as const}:{}),timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const time=(s:string)=>{const [h,m]=s.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'pm':'am'}`;};
const complete=(p:Entry={})=>stages.every(s=>p[s]);
const pct=(a:number,b:number)=>b?Math.round(a/b*100):0;
const hrs=(n:number)=>Number(n.toFixed(2));
const subjectColor=(s:string)=>colors[subjects.indexOf(s)%colors.length]||'#2f7c75';
function Meter({value}:{value:number}){return <div className="meter" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${value}%`}}/></div>;}
function LogEditor({value,save,saving,task=false}:{value:Entry;save:(v:Entry)=>Promise<boolean>;saving:boolean;task?:boolean}){
 const dirty=useRef(false);
 const [hours,setHours]=useState(value.hours==null?'':String(value.hours)),[notes,setNotes]=useState(value.notes||''),[message,setMessage]=useState('');
 useEffect(()=>{if(dirty.current)return;setHours(value.hours==null?'':String(value.hours));setNotes(value.notes||'');},[value.hours,value.notes]);
 return <form className="log-editor" onSubmit={async e=>{e.preventDefault();setMessage('');const n=hours===''?null:Number(hours);if(task&&n!==null&&(!Number.isFinite(n)||n<0||n>24)){setMessage('Enter 0–24 hours.');return;}if(await save({...value,notes,...(task?{hours:n}:{})})){dirty.current=false;setMessage('Saved');}else setMessage('Not saved — your text is kept here. Retry when ready.');}}>{task&&<label>Actual hours<input type="number" min="0" max="24" step="0.05" value={hours} onChange={e=>{dirty.current=true;setHours(e.target.value);setMessage('');}} placeholder="e.g. 1.5"/><small>Ticking a task does not add hours.</small></label>}<label className="notes-label">{task?'Notes / test score':'Doubts / notes'}<textarea maxLength={2000} rows={2} value={notes} onChange={e=>{dirty.current=true;setNotes(e.target.value);setMessage('');}} placeholder={task?'What did you finish or find difficult?':'A concept or question to revisit…'}/></label><button type="submit" className="primary" disabled={saving}>{saving?'Saving…':'Save'}</button><span className="save-message" role="status">{message}</span></form>;
}
export default function Tracker({localMode=false}:{localMode?:boolean}){
 const [view,setView]=useState<View>('Today'),[selected,setSelected]=useState('2026-10-06'),[today,setToday]=useState('2026-10-06');
 const [progress,setProgress]=useState<Progress>({}),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState<Record<string,boolean>>({});
 const [subject,setSubject]=useState('All subjects'),[query,setQuery]=useState(''),[moduleFilter,setModuleFilter]=useState(''),[filter,setFilter]=useState('All topics'),[pastDue,setPastDue]=useState(false);
 const savingIds=useRef(new Set<string>()),stateRef=useRef(progress);stateRef.current=progress;
 async function load(){setLoading(true);setLoadError('');try{const r=await fetch('/api/progress',{cache:'no-store'});const b=await r.json() as {progress:Progress;error?:string};if(!r.ok)throw new Error(b.error);setProgress(b.progress);}catch(e){setLoadError(e instanceof Error?e.message:'Could not load your progress.');}finally{setLoading(false);}}
 useEffect(()=>{const d=actualToday();setToday(d);setSelected(clampDate(d));void load();},[]);
 async function save(id:string,value:Entry){if(savingIds.current.has(id)||loading||loadError)return false;savingIds.current.add(id);const before=stateRef.current[id]||{};setBusy(b=>({...b,[id]:true}));setError('');setProgress(p=>({...p,[id]:value}));try{const r=await fetch('/api/progress',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,value})});const b=await r.json() as {progress:Progress;error?:string};if(!r.ok)throw new Error(b.error);return true;}catch(e){setProgress(p=>({...p,[id]:before}));setError(e instanceof Error?e.message:'Could not save. Please try again.');return false;}finally{savingIds.current.delete(id);setBusy(b=>({...b,[id]:false}));}}
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
  const ctx=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!ctx?.registerTool)return;
  const controller=new AbortController();
  const tools:Tool[]=[{name:'get_study_progress',description:'Read saved topic completion and actual study hours for the current signed-in learner.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const r=await fetch('/api/progress',{cache:'no-store'}),b=await r.json() as {progress:Progress;error?:string};if(!r.ok)throw Error(b.error);setProgress(b.progress);const p:Progress=b.progress;return{topicsCompleted:plan.topics.filter(t=>complete(p[t.id])).length,topicsTotal:plan.topics.length,actualHours:hrs(plan.tasks.reduce((s,t)=>s+(p[t.id]?.hours||0),0))};}},{name:'view_study_day',description:'Show the dated daily checklist without marking tasks complete.',inputSchema:{type:'object',properties:{date:{type:'string',format:'date'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('date'in input)||typeof input.date!=='string'||!dates.includes(input.date))throw Error('Choose a date between 2026-10-06 and 2027-02-05.');const d=input.date;setSelected(d);setPastDue(false);setView('Today');return{date:d,tasks:plan.tasks.filter(t=>t.date===d).length};}}];
  for(const tool of tools)try{void Promise.resolve(ctx.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}
  return()=>controller.abort();
 },[]);
 const locked=loading||!!loadError;
 const learned=plan.topics.filter(t=>progress[t.id]?.lesson).length,finished=plan.topics.filter(t=>complete(progress[t.id])).length;
 const totalHours=hrs(plan.tasks.reduce((s,t)=>s+(progress[t.id]?.hours||0),0));
 const dayTasks=plan.tasks.filter(t=>t.date===selected),dayDone=dayTasks.filter(t=>progress[t.id]?.done).length,dayHours=hrs(dayTasks.reduce((s,t)=>s+(progress[t.id]?.hours||0),0));
 const overdue=plan.tasks.filter(t=>t.date<today&&!progress[t.id]?.done),shownTasks=pastDue?overdue:dayTasks;
 const filteredTopics=plan.topics.filter(t=>(subject==='All subjects'||t.subject===subject)&&(!moduleFilter||t.moduleId===moduleFilter)&&(!query||`${t.name} ${t.subject}`.toLowerCase().includes(query.toLowerCase()))&&(filter==='All topics'||(filter==='Completed'?complete(progress[t.id]):!complete(progress[t.id]))));
 function openModule(id:string){setModuleFilter(id);setSubject('All subjects');setQuery('');setFilter('All topics');setView('Syllabus');window.scrollTo({top:0,behavior:'smooth'});}
 const navIcons=[CalendarDays,BookOpen,Layers3,ChartNoAxesCombined];
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="brand-mark"><CheckCheck size={26}/></span><div>Study Studio<small>GATE DA 2027</small></div></div><nav aria-label="Main navigation">{(['Today','Syllabus','Modules','Progress'] as View[]).map((v,i)=>{const Icon=navIcons[i];return <button key={v} className={view===v?'active':''} aria-current={view===v?'page':undefined} onClick={()=>{setView(v);window.scrollTo({top:0});}}><Icon size={20}/>{v}</button>;})}</nav><div className="sidebar-progress"><small>Full syllabus completion</small><strong>{locked?'—':pct(finished,plan.topics.length)}%</strong><Meter value={pct(finished,plan.topics.length)}/><span>{locked?'Loading':`${finished} of ${plan.topics.length} topics`}</span></div><div className="sidebar-foot">YOUR FOUR-MONTH PLAN<br/>6 Oct 2026 – 5 Feb 2027<br/>{localMode?<span>Stored on this computer</span>:<a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a>}</div></aside><main><header className="page-header"><div><div className="eyebrow">GATE DA / {view.toUpperCase()}</div><h1>{view==='Today'?'One session at a time.':view==='Syllabus'?'Make every topic count.':view==='Modules'?'Your four-month roadmap.':'See your learning add up.'}</h1><p>{view==='Today'?pretty(selected,true):view==='Syllabus'?'Track lessons, practice, previous-year questions and revision.':view==='Modules'?'29 modules, with machine learning in parallel from November.':'Lesson coverage, completed topics and time you actually studied.'}</p></div><span className="sync-state" role="status">{loading?'Loading progress…':loadError?'Progress unavailable':error?'Save failed — please retry':Object.values(busy).some(Boolean)?'Saving…':<><Check size={16}/> {localMode?'Saved on this computer':'Saved to your account'}</>}</span></header>
 {loadError&&<div className="alert" role="alert">{loadError}<button onClick={()=>void load()}><RefreshCw size={16}/> Retry</button>{!localMode&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in</a>}</div>}{error&&<div className="alert" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {view==='Today'&&<><section className="stats"><article><small>Sessions completed</small><strong>{locked?'—':dayDone} <span>/ {dayTasks.length}</span></strong><Meter value={pct(dayDone,dayTasks.length)}/></article><article><small>Actual study time today</small><strong>{locked?'—':dayHours} <span>/ {hrs(dayTasks.reduce((s,t)=>s+t.hours,0))}h planned</span></strong></article><article><small>Topics fully completed</small><strong>{locked?'—':finished} <span>/ {plan.topics.length}</span></strong><small>All four learning stages ticked</small></article></section>
 <div className="day-toolbar"><div className="date-controls"><button aria-label="Previous study day" disabled={selected===dates[0]} onClick={()=>{setSelected(dates[dates.indexOf(selected)-1]);setPastDue(false);}}><ChevronLeft size={20}/></button><input aria-label="Study date" type="date" value={selected} min={dates[0]} max={dates.at(-1)} onChange={e=>{if(dates.includes(e.target.value)){setSelected(e.target.value);setPastDue(false);}}}/><button aria-label="Next study day" disabled={selected===dates.at(-1)} onClick={()=>{setSelected(dates[dates.indexOf(selected)+1]);setPastDue(false);}}><ChevronRight size={20}/></button><button onClick={()=>{setSelected(clampDate(today));setPastDue(false);}}>Today</button></div><button className={pastDue?'chip selected':'chip'} onClick={()=>setPastDue(!pastDue)}>{pastDue?'Show selected day':`Past due (${locked?'—':overdue.length})`}</button></div>
 <div className="section-head"><h2>{pastDue?'Unfinished earlier sessions':'Your schedule'}</h2><span>{selected>='2027-01-01'?'Revision and mock phase':'First-pass learning'}</span></div><section className="schedule">{shownTasks.length===0?<div className="empty"><CheckCheck size={32}/><h3>No unfinished earlier sessions</h3><p>Your earlier scheduled tasks are checked off.</p></div>:shownTasks.map(t=>{const p=progress[t.id]||{};return <article className={`session ${p.done?'session-done':''}`} key={t.id}><div className="session-row"><input type="checkbox" checked={!!p.done} disabled={locked||busy[t.id]} onChange={e=>void save(t.id,{...p,done:e.target.checked})} aria-label={`Complete ${t.activity} on ${t.date} at ${t.start}`}/><div className="time">{time(t.start)}<small>{time(t.end)}</small>{pastDue&&<small>{pretty(t.date)}</small>}</div><div className="session-main"><span className="tag" style={{color:subjectColor(t.subject)}}>{t.subject}</span><h3>{t.activity}</h3><p>{t.target}</p></div><span className="planned"><Clock3 size={15}/>{t.hours}h</span></div><details className="task-details"><summary>{p.hours!=null?`${p.hours}h logged · `:''}{p.notes?'Edit notes & time':'Log time & notes'}</summary><LogEditor value={p} task saving={locked||busy[t.id]} save={v=>save(t.id,v)}/></details></article>;})}</section><p className="hint">Breaks: 12–12:15 pm, lunch 1:45–2:45 pm, 4:15–4:45 pm and dinner 6:15–7:30 pm. Sundays and mock days use their own schedule.</p></>}
 {view==='Syllabus'&&<><div className="syllabus-summary"><div><strong>{locked?'—':learned}</strong> lessons learned</div><div><strong>{locked?'—':finished}</strong> topics fully completed</div><div><strong>150</strong> checklist items</div></div><div className="filters"><label className="search"><Search size={18}/><input aria-label="Search syllabus" placeholder="Find a topic…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Subject" value={subject} onChange={e=>{setSubject(e.target.value);setModuleFilter('');}}><option>All subjects</option>{subjects.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Completion filter" value={filter} onChange={e=>setFilter(e.target.value)}>{['All topics','To complete','Completed'].map(s=><option key={s}>{s}</option>)}</select></div>{moduleFilter&&<div className="filter-note">Showing {plan.modules.find(m=>m.id===moduleFilter)?.name}<button onClick={()=>setModuleFilter('')}>Clear module filter</button></div>}
 {filteredTopics.length===0&&<div className="empty"><h3>No matching topics</h3><p>Try another search or clear your filters.</p></div>}
 {plan.modules.filter(m=>filteredTopics.some(t=>t.moduleId===m.id)).map(m=><details className="topic-group" key={m.id} open={!!moduleFilter||!!query||subject!=='All subjects'}><summary><div><span className="module-code">{m.id}</span><strong>{m.name}</strong><small>{m.subject} · Target {pretty(m.end)}</small></div><span>{plan.topics.filter(t=>t.moduleId===m.id&&complete(progress[t.id])).length}/{plan.topics.filter(t=>t.moduleId===m.id).length} complete</span></summary><div className="topic-list">{filteredTopics.filter(t=>t.moduleId===m.id).map(t=>{const p=progress[t.id]||{};return <div className="topic" key={t.id}><div className="topic-top"><h3>{t.name}</h3>{complete(p)&&<span className="complete-label"><Check size={15}/> Complete</span>}</div><div className="stages">{stages.map((s,i)=><label className={p[s]?'stage checked':'stage'} key={s}><input type="checkbox" checked={!!p[s]} disabled={locked||busy[t.id]} onChange={e=>void save(t.id,{...p,[s]:e.target.checked})}/>{stageLabels[i]}</label>)}</div><details className="topic-notes"><summary>{p.notes?'Edit saved notes':'Add a doubt or note'}</summary><LogEditor value={p} saving={locked||busy[t.id]} save={v=>save(t.id,v)}/></details></div>;})}</div></details>)}<div className="source-note"><p>Based on the official 2027 syllabus, grouped into your study modules. Full completion means all four stages; each topic counts equally. For topics without a direct PYQ, practise relevant exam-style questions.</p><a href="https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/DA_GATE2027_Syllabus.pdf" target="_blank" rel="noreferrer">Official DA syllabus <ExternalLink size={14}/></a><a href="https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/GA_GATE2027_Syllabus.pdf" target="_blank" rel="noreferrer">Official aptitude syllabus <ExternalLink size={14}/></a></div></>}
 {view==='Modules'&&<><div className="phase-strip">{[['01','OCT–EARLY NOV','Maths foundations'],['02','NOV–DEC','Other subjects + ML'],['03','JAN–5 FEB','Revision + mocks']].map(([n,d,l])=><div key={n}><span>{n}</span><div><small>{d}</small><strong>{l}</strong></div></div>)}</div><div className="module-grid">{plan.modules.map(m=>{const ts=plan.topics.filter(t=>t.moduleId===m.id),done=ts.filter(t=>complete(progress[t.id])).length,lessons=ts.filter(t=>progress[t.id]?.lesson).length;return <button className="module-card" key={m.id} onClick={()=>openModule(m.id)} style={{borderTopColor:subjectColor(m.subject)}}><div className="module-meta"><span>{m.id}</span><span>{pretty(m.start)} – {pretty(m.end)}</span></div><small>{m.subject}</small><h3>{m.name}</h3><Meter value={pct(done,ts.length)}/><div className="module-bottom"><span>{lessons}/{ts.length} lessons</span><strong>{pct(done,ts.length)}% complete</strong></div></button>;})}</div><p className="hint">Module dates are preparation targets, not verified GO Classes lecture durations. Review your pace each Sunday. January is reserved for revision and mocks.</p></>}
 {view==='Progress'&&<><section className="stats"><article><small>Full syllabus completion</small><strong>{locked?'—':pct(finished,plan.topics.length)}<span>%</span></strong><Meter value={pct(finished,plan.topics.length)}/></article><article><small>Lesson coverage</small><strong>{locked?'—':pct(learned,plan.topics.length)}<span>%</span></strong><small>{learned} of {plan.topics.length} lessons</small></article><article><small>Actual hours studied</small><strong>{locked?'—':totalHours}<span> h</span></strong><small>{plan.tasks.filter(t=>progress[t.id]?.done).length} sessions checked off</small></article></section><div className="progress-grid"><section className="panel"><h2>Subject progress</h2>{subjects.map(s=>{const ts=plan.topics.filter(t=>t.subject===s),done=ts.filter(t=>complete(progress[t.id])).length;return <div className="subject-progress" key={s}><div><strong>{s}</strong><span>{done}/{ts.length}</span></div><Meter value={pct(done,ts.length)}/></div>;})}</section><section className="panel"><h2>Hours by month</h2><p className="hint">Actual time entered in daily sessions.</p>{['2026-10','2026-11','2026-12','2027-01','2027-02'].map(month=>{const actual=hrs(plan.tasks.filter(t=>t.date.startsWith(month)).reduce((s,t)=>s+(progress[t.id]?.hours||0),0)),planned=hrs(plan.tasks.filter(t=>t.date.startsWith(month)).reduce((s,t)=>s+t.hours,0));return <div className="month-row" key={month}><div><strong>{new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(new Date(month+'-15'))}</strong><span>{actual}h <small>/ {planned}h planned</small></span></div><Meter value={Math.min(100,pct(actual,planned))}/></div>;})}<div className="progress-note"><BookOpen size={20}/><p>A checked lesson means you studied it. A completed topic also includes practice, PYQs and revision. These percentages track preparation, not a predicted GATE score.</p></div></section></div></>}
 </main></div>;
}
